#include "catch_amalgamated.hpp"
#include "nn/core/inference_pipeline_metrics.h"

TEST_CASE("Inference pipeline metrics expose host, graph, and RKNN stage timings",
          "[nn][rknn][metrics]") {
    cosmo::nn::InferencePipelineMetrics metrics;

    metrics.RecordColorConvert(2'000'000, 2);
    metrics.RecordBlobConvert(3'000'000, 2);
    metrics.RecordGraphForward(8'000'000, 2, true);
    metrics.RecordGraphForward(1'000'000, 1, false);
    metrics.RecordResultParse(4'000'000, 2, true);
    metrics.RecordResultParse(500'000, 1, false);
    constexpr auto detector = cosmo::nn::RknnModelScope::Detector;
    metrics.RecordRknnPrepare(1'000'000, detector);
    metrics.RecordRknnInputsSet(2'000'000, detector);
    metrics.RecordRknnRun(3'000'000, detector);
    metrics.RecordRknnOutputsGet(4'000'000, detector);
    metrics.RecordRknnOutputsRelease(400'000, detector);
    metrics.RecordRknnOutputTransform(5'000'000, detector);
    metrics.RecordRknnForward(15'000'000, true, detector);
    metrics.RecordRknnForward(7'000'000, false, detector);
    metrics.RecordRknnMutexWait(600'000, detector);
    metrics.RecordRknnPreprocessFastHit();
    metrics.RecordRknnRgaFill(700'000);
    metrics.RecordRknnRgaResizeColor(800'000);
    metrics.RecordRknnRgaFailure();
    metrics.RecordRknnCpuResizeFallback(900'000);
    metrics.RecordRknnCpuNormalizeFallback(1'000'000);
    metrics.RecordRknnNativeInputMap(1'100'000);
    metrics.RecordRknnInputFormat(true);
    metrics.RecordRknnInputFormat(false, true);
    metrics.RecordRknnOutputFormat(true, 1'225'600);
    metrics.RecordRknnOutputFormat(false, 4'902'400, true);
    metrics.RecordRknnYolov8Transform(1'400'000, 1'500'000);
    metrics.RecordRknnYolov8DirectCandidates(true, 8'400, 17, 2'822'400);
    metrics.RecordRknnYolov8DirectCandidates(false, 0, 0, 0);
    metrics.RecordYolov8Postprocess(1'200'000);
    metrics.RecordYolov8Nms(1'300'000);

    const auto snapshot = metrics.Snapshot();
    CHECK(snapshot.color_convert_frames == 2);
    CHECK(snapshot.color_convert_nanoseconds == 2'000'000);
    CHECK(snapshot.blob_convert_frames == 2);
    CHECK(snapshot.graph_forward_frames == 3);
    CHECK(snapshot.graph_forward_nanoseconds == 9'000'000);
    CHECK(snapshot.graph_forward_failures == 1);
    CHECK(snapshot.result_parse_frames == 3);
    CHECK(snapshot.result_parse_failures == 1);
    CHECK(snapshot.rknn_forwards == 2);
    CHECK(snapshot.rknn_forward_nanoseconds == 22'000'000);
    CHECK(snapshot.rknn_forward_failures == 1);
    CHECK(snapshot.rknn_prepare_calls == 1);
    CHECK(snapshot.rknn_inputs_set_calls == 1);
    CHECK(snapshot.rknn_run_calls == 1);
    CHECK(snapshot.rknn_outputs_get_calls == 1);
    CHECK(snapshot.rknn_outputs_release_calls == 1);
    CHECK(snapshot.rknn_outputs_release_nanoseconds == 400'000);
    CHECK(snapshot.rknn_output_transform_calls == 1);
    CHECK(snapshot.rknn_mutex_wait_calls == 1);
    CHECK(snapshot.rknn_mutex_wait_nanoseconds == 600'000);
    CHECK(snapshot.rknn_detector_forwards == 2);
    CHECK(snapshot.rknn_detector_forward_nanoseconds == 22'000'000);
    CHECK(snapshot.rknn_detector_forward_failures == 1);
    CHECK(snapshot.rknn_detector_prepare_calls == 1);
    CHECK(snapshot.rknn_detector_inputs_set_calls == 1);
    CHECK(snapshot.rknn_detector_run_calls == 1);
    CHECK(snapshot.rknn_detector_outputs_get_calls == 1);
    CHECK(snapshot.rknn_detector_outputs_release_calls == 1);
    CHECK(snapshot.rknn_detector_output_transform_calls == 1);
    CHECK(snapshot.rknn_detector_mutex_wait_calls == 1);
    CHECK(snapshot.rknn_preprocess_fast_hits == 1);
    CHECK(snapshot.rknn_rga_fill_calls == 1);
    CHECK(snapshot.rknn_rga_resize_color_calls == 1);
    CHECK(snapshot.rknn_rga_failures == 1);
    CHECK(snapshot.rknn_cpu_resize_fallback_calls == 1);
    CHECK(snapshot.rknn_cpu_normalize_fallback_calls == 1);
    CHECK(snapshot.rknn_native_input_map_calls == 1);
    CHECK(snapshot.rknn_native_int8_inputs == 1);
    CHECK(snapshot.rknn_float_inputs == 1);
    CHECK(snapshot.rknn_input_compatibility_fallbacks == 1);
    CHECK(snapshot.rknn_native_int8_outputs == 1);
    CHECK(snapshot.rknn_float_outputs == 1);
    CHECK(snapshot.rknn_output_compatibility_fallbacks == 1);
    CHECK(snapshot.rknn_native_output_bytes == 1'225'600);
    CHECK(snapshot.rknn_float_output_bytes == 4'902'400);
    CHECK(snapshot.rknn_yolov8_dfl_calls == 1);
    CHECK(snapshot.rknn_yolov8_dfl_nanoseconds == 1'400'000);
    CHECK(snapshot.rknn_yolov8_class_calls == 1);
    CHECK(snapshot.rknn_yolov8_class_nanoseconds == 1'500'000);
    CHECK(snapshot.rknn_yolov8_direct_candidate_calls == 2);
    CHECK(snapshot.rknn_yolov8_direct_candidate_failures == 1);
    CHECK(snapshot.rknn_yolov8_direct_points_scanned == 8'400);
    CHECK(snapshot.rknn_yolov8_direct_points_decoded == 17);
    CHECK(snapshot.rknn_yolov8_logical_float_bytes_avoided == 2'822'400);
    CHECK(snapshot.yolov8_postprocess_calls == 1);
    CHECK(snapshot.yolov8_nms_calls == 1);
}
